"use client";
import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import { ChevronDown, UserRound, UserCog, Settings, Library, MessageCircle, Compass, Video, LogOut } from "lucide-react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";
import { westernDigits } from "@/lib/ravine-format";
type Locale="ar"|"en"; type Props={locale:Locale;displayName:string;username:string|null;avatarUrl:string|null;isCreator:boolean};
export default function AccountMenu({locale,displayName,username,avatarUrl,isCreator}:Props){
 const ar=locale==="ar"; const router=useRouter(); const rootRef=useRef<HTMLDivElement>(null); const [open,setOpen]=useState(false); const [signingOut,setSigningOut]=useState(false);
 useEffect(()=>{const down=(e:PointerEvent)=>{if(!rootRef.current?.contains(e.target as Node))setOpen(false)};const key=(e:KeyboardEvent)=>{if(e.key==="Escape")setOpen(false)};document.addEventListener("pointerdown",down);document.addEventListener("keydown",key);return()=>{document.removeEventListener("pointerdown",down);document.removeEventListener("keydown",key)}},[]);
 async function signOut(){setSigningOut(true);const s=createClient();await s.auth.signOut();setOpen(false);router.replace(`/${locale}`);router.refresh()}
 const safeDisplayName=westernDigits(displayName||""); const safeUsername=username?westernDigits(username):null; const fallback=(safeDisplayName||safeUsername||"R").trim().slice(0,1).toUpperCase();
 return <div ref={rootRef} className={`ravine-account-menu${open?" is-open":""}`} dir={ar?"rtl":"ltr"}><button type="button" className="ravine-account-trigger" aria-haspopup="menu" aria-expanded={open} onClick={()=>setOpen(v=>!v)} title={safeDisplayName||(ar?"حسابك":"Your account")}><span className="ravine-account-avatar">{avatarUrl?<img src={avatarUrl} alt=""/>:<span>{fallback}</span>}</span><ChevronDown size={14}/></button>{open?<div className="ravine-account-panel" role="menu"><div className="ravine-account-summary"><div className="ravine-account-avatar large">{avatarUrl?<img src={avatarUrl} alt=""/>:<span>{fallback}</span>}</div><div className="ravine-account-summary-copy"><strong>{safeDisplayName||"RAVINE"}</strong><span>{safeUsername?`@${safeUsername}`:(ar?"هوية شخصية":"Personal identity")}</span></div></div><div className="ravine-account-section-label">{ar?"الحساب":"Account"}</div><Link href={`/${locale}/account`} onClick={()=>setOpen(false)} role="menuitem"><UserRound size={16}/>{ar?"عرض الحساب":"View account"}</Link><Link href={`/${locale}/account/edit`} onClick={()=>setOpen(false)} role="menuitem"><UserCog size={16}/>{ar?"تعديل الملف الشخصي":"Edit profile"}</Link><Link href={`/${locale}/settings`} onClick={()=>setOpen(false)} role="menuitem"><Settings size={16}/>{ar?"الإعدادات العامة":"General settings"}</Link><div className="ravine-account-section-label">{ar?"مساحتك":"Your space"}</div><Link href={`/${locale}/library`} onClick={()=>setOpen(false)} role="menuitem"><Library size={16}/>{ar?"المكتبة":"Library"}</Link><Link href={`/${locale}/messages`} onClick={()=>setOpen(false)} role="menuitem"><MessageCircle size={16}/>{ar?"الرسائل":"Messages"}</Link><Link href={`/${locale}/community`} onClick={()=>setOpen(false)} role="menuitem"><MessageCircle size={16}/>{ar?"المجتمعات":"Communities"}</Link><Link href={`/${locale}/discover`} onClick={()=>setOpen(false)} role="menuitem"><Compass size={16}/>{ar?"الاكتشاف":"Discover"}</Link><div className="ravine-account-section-label">{ar?"لوحتك":"Dashboard"}</div><Link href={`/${locale}/dashboard`} onClick={()=>setOpen(false)} role="menuitem"><Video size={16}/>{ar?"لوحة المستخدم":"User dashboard"}</Link>{isCreator?<Link href={`/${locale}/studio`} onClick={()=>setOpen(false)} role="menuitem"><Video size={16}/>{ar?"استوديو المبدع":"Creator Studio"}</Link>:null}<div className="ravine-account-divider"/><button type="button" className="ravine-account-signout" onClick={()=>void signOut()} disabled={signingOut} role="menuitem"><LogOut size={16}/>{signingOut?(ar?"جارٍ الخروج…":"Signing out…"):(ar?"تسجيل الخروج":"Sign out")}</button></div>:null}</div>
}