"use client";
import { ChangeEvent, PointerEvent, useEffect, useRef, useState } from "react";
import { Check, ImagePlus, Maximize2, Minus, Plus, RotateCcw } from "lucide-react";

type Aspect="square"|"cover";
type Props={aspect:Aspect;locale:"ar"|"en";value:File|null;existingUrl?:string|null;onChange:(file:File|null)=>void};
const T={ar:{choose:"اختيار صورة",change:"تغيير الصورة",adjust:"تعديل الإطار",avatar:"الصورة الشخصية · 1:1",cover:"الغلاف السينمائي · 16:9",hint:"الصورة ثابتة عند المقاس الطبيعي. كبّرها أولًا لتتمكن من تحريكها.",apply:"اعتماد القص",applied:"تم اعتماد القص",reset:"إعادة ضبط",zoomIn:"تكبير",zoomOut:"تصغير"},en:{choose:"Choose image",change:"Change image",adjust:"Adjust frame",avatar:"Profile image · 1:1",cover:"Cinematic cover · 16:9",hint:"The image stays fixed at natural fit. Zoom first to move it.",apply:"Apply crop",applied:"Crop applied",reset:"Reset",zoomIn:"Zoom in",zoomOut:"Zoom out"}};
const srcOf=(u:string|null|undefined)=>!u?null:u.startsWith("blob:")||u.startsWith("data:")?u:`/api/profile-image-proxy?url=${encodeURIComponent(u)}`;
export default function RavineMediaPicker({aspect,locale,value,existingUrl,onChange}:Props){
 const c=T[locale],ar=locale==="ar",ratio=aspect==="square"?1:16/9,out=aspect==="square"?[1200,1200]:[1600,900];
 const input=useRef<HTMLInputElement>(null),view=useRef<HTMLDivElement>(null),image=useRef<HTMLImageElement>(null),drag=useRef({x:0,y:0,ox:0,oy:0});
 const [url,setUrl]=useState(srcOf(existingUrl)),[natural,setNatural]=useState({w:0,h:0}),[zoom,setZoom]=useState(1),[offset,setOffset]=useState({x:0,y:0}),[moving,setMoving]=useState(false),[dirty,setDirty]=useState(false),[applied,setApplied]=useState(Boolean(value)),[error,setError]=useState(false);
 useEffect(()=>{if(value)return;setUrl(srcOf(existingUrl));setNatural({w:0,h:0});setZoom(1);setOffset({x:0,y:0});setDirty(false);setApplied(false);setError(false)},[existingUrl,value]);
 useEffect(()=>()=>{if(url?.startsWith("blob:"))URL.revokeObjectURL(url)},[url]);
 const metrics=()=>{const e=view.current;if(!e||!natural.w)return null;const w=e.clientWidth,h=w/ratio,b=Math.min(w/natural.w,h/natural.h),s=b*zoom;return{w,h,s,iw:natural.w*s,ih:natural.h*s}};
 const clamp=(x:number,y:number)=>{const m=metrics();if(!m)return{x:0,y:0};const lx=Math.max(0,(m.iw-m.w)/2),ly=Math.max(0,(m.ih-m.h)/2);return{x:Math.max(-lx,Math.min(lx,x)),y:Math.max(-ly,Math.min(ly,y))}};
 const changed=()=>{setDirty(true);setApplied(false);setError(false)};
 function onFile(e:ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;setUrl(URL.createObjectURL(f));setNatural({w:0,h:0});setZoom(1);setOffset({x:0,y:0});changed();e.target.value=""}
 function start(e:PointerEvent<HTMLDivElement>){if(!url||zoom<=1)return;drag.current={x:e.clientX,y:e.clientY,ox:offset.x,oy:offset.y};setMoving(true);e.currentTarget.setPointerCapture(e.pointerId)}
 function move(e:PointerEvent<HTMLDivElement>){if(!moving)return;setOffset(clamp(drag.current.ox+e.clientX-drag.current.x,drag.current.oy+e.clientY-drag.current.y));changed()}
 function end(e:PointerEvent<HTMLDivElement>){setMoving(false);if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId)}
 function zoomTo(n:number){const z=Math.max(1,Math.min(2.8,n));setZoom(z);requestAnimationFrame(()=>setOffset(o=>clamp(o.x,o.y)));changed()}
 async function apply(){const m=metrics(),i=image.current;if(applied||!m||!i||!natural.w)return;try{const cv=document.createElement("canvas");cv.width=out[0];cv.height=out[1];const x=cv.getContext("2d");if(!x||!i.complete||!i.naturalWidth)throw new Error();const sw=Math.min(natural.w,m.w/m.s),sh=Math.min(natural.h,m.h/m.s),sx=Math.max(0,Math.min(natural.w-sw,(natural.w-sw)/2-offset.x/m.s)),sy=Math.max(0,Math.min(natural.h-sh,(natural.h-sh)/2-offset.y/m.s));x.imageSmoothingEnabled=true;x.imageSmoothingQuality="high";x.drawImage(i,sx,sy,sw,sh,0,0,out[0],out[1]);const b=await new Promise<Blob|null>((resolve,reject)=>{try{cv.toBlob(resolve,"image/webp",.9)}catch(e){reject(e)}});if(!b)throw new Error();onChange(new File([b],aspect==="square"?"ravine-avatar.webp":"ravine-cover.webp",{type:"image/webp"}));setDirty(false);setApplied(true);setError(false)}catch{setApplied(false);setError(true)}}
 const m=natural.w?metrics():null;const style=m?{position:"absolute" as const,width:m.iw,height:m.ih,left:`calc(50% - ${m.iw/2}px + ${offset.x}px)`,top:`calc(50% - ${m.ih/2}px + ${offset.y}px)`,objectFit:"fill" as const,transition:moving?"none":"transform 180ms cubic-bezier(.22,1,.36,1)",transform:"none",willChange:"transform"}:undefined;
 return <div className={`ravine-media-picker ravine-media-picker--${aspect}`} dir={ar?"rtl":"ltr"}><input ref={input} className="ravine-media-picker-input" type="file" accept="image/jpeg,image/png,image/webp" onChange={onFile}/><div className="ravine-media-picker-head"><div><span>{aspect==="square"?c.avatar:c.cover}</span><strong>{applied?c.applied:dirty?c.adjust:url?c.change:c.choose}</strong></div><span className="ravine-media-ratio">{aspect==="square"?"1:1":"16:9"}</span></div>{url?<><div ref={view} className={`ravine-media-crop${applied?" is-applied":""}`} onPointerDown={start} onPointerMove={move} onPointerUp={end} onPointerCancel={end} style={{aspectRatio:`${ratio}`}}><img ref={image} src={url} alt="" onLoad={()=>{const i=image.current;if(i)setNatural({w:i.naturalWidth,h:i.naturalHeight})}} onError={()=>setError(true)} className="ravine-media-crop-image" style={style} draggable={false}/><div className="ravine-media-crop-frame"/>{applied&&<div className="ravine-media-crop-applied"><Check size={16}/><span>{c.applied}</span></div>}{!applied&&zoom===1&&<div className="ravine-media-crop-hint">{c.hint}</div>}</div><div className="ravine-media-controls"><button type="button" className="ravine-media-icon-button" onClick={()=>zoomTo(zoom-.1)} disabled={zoom<=1} aria-label={c.zoomOut}><Minus size={14}/></button><label className="ravine-media-zoom"><span>{Math.round(zoom*100)}%</span><input type="range" min="1" max="2.8" step=".01" value={zoom} onChange={e=>zoomTo(Number(e.target.value))} aria-label={ar?"تكبير الصورة":"Image zoom"}/></label><button type="button" className="ravine-media-icon-button" onClick={()=>zoomTo(zoom+.1)} disabled={zoom>=2.8} aria-label={c.zoomIn}><Plus size={14}/></button><button type="button" className="ravine-media-icon-button" onClick={()=>{setZoom(1);setOffset({x:0,y:0});changed()}} aria-label={c.reset}><RotateCcw size={15}/></button><button type="button" className="ravine-media-change" onClick={()=>input.current?.click()}><Maximize2 size={14}/>{c.change}</button>{applied?<button type="button" className="ravine-media-applied" disabled><Check size={14}/>{c.applied}</button>:dirty?<button type="button" className="ravine-media-apply" onClick={()=>void apply()}><Check size={14}/>{c.apply}</button>:null}</div></>:<button type="button" className="ravine-media-empty" onClick={()=>input.current?.click()}><span className="ravine-media-empty-icon"><ImagePlus size={20}/></span><strong>{c.choose}</strong></button>}{error&&<div className="ravine-media-crop-hint">{ar?"تعذر قراءة الصورة أو قصها.":"The image could not be read or cropped."}</div>}</div>;
}