"use client";
import { ChangeEvent, PointerEvent, useEffect, useRef, useState } from "react";
import { Check, ImagePlus, Minus, Plus, RotateCcw } from "lucide-react";

type Props={aspect:"square"|"cover";locale:"ar"|"en";existingUrl?:string|null;value:File|null;onChange:(file:File|null)=>void};
const C={ar:{choose:"اختيار صورة",change:"تغيير الصورة",apply:"اعتماد القص",applied:"تم اعتماد القص",zoomIn:"تكبير",zoomOut:"تصغير",reset:"إعادة ضبط",hint:"اسحب فقط بعد التكبير لضبط الكادر."},en:{choose:"Choose image",change:"Change image",apply:"Apply crop",applied:"Crop applied",zoomIn:"Zoom in",zoomOut:"Zoom out",reset:"Reset",hint:"Drag only after zooming to refine the frame."}};
const proxy=(u:string|null|undefined)=>!u?null:u.startsWith("blob:")||u.startsWith("data:")?u:`/api/profile-image-proxy?url=${encodeURIComponent(u)}`;
export default function RavineMediaCropper({aspect,locale,existingUrl,value,onChange}:Props){
 const ar=locale==="ar",c=C[locale],ratio=aspect==="square"?1:16/9,out=aspect==="square"?[1200,1200]:[1600,900];
 const v=useRef<HTMLDivElement>(null),img=useRef<HTMLImageElement>(null),drag=useRef({x:0,y:0,ox:0,oy:0});
 const [src,setSrc]=useState(proxy(existingUrl)),[size,setSize]=useState({w:0,h:0}),[zoom,setZoom]=useState(1),[offset,setOffset]=useState({x:0,y:0}),[moving,setMoving]=useState(false),[dirty,setDirty]=useState(false),[applied,setApplied]=useState(Boolean(value)),[error,setError]=useState(false);
 useEffect(()=>{if(value)return;setSrc(proxy(existingUrl));setSize({w:0,h:0});setZoom(1);setOffset({x:0,y:0});setDirty(false);setApplied(false);setError(false)},[existingUrl,value]);
 useEffect(()=>()=>{if(src?.startsWith("blob:"))URL.revokeObjectURL(src)},[src]);
 const metrics=()=>{const el=v.current;if(!el||!size.w)return null;const w=el.clientWidth,h=w/ratio,b=Math.min(w/size.w,h/size.h),s=b*zoom;return{w,h,s,iw:size.w*s,ih:size.h*s}};
 const clamp=(x:number,y:number)=>{const m=metrics();if(!m)return{x:0,y:0};const lx=Math.max(0,(m.iw-m.w)/2),ly=Math.max(0,(m.ih-m.h)/2);return{x:Math.max(-lx,Math.min(lx,x)),y:Math.max(-ly,Math.min(ly,y))}};
 const changed=()=>{setDirty(true);setApplied(false);setError(false)};
 function file(e:ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;setSrc(URL.createObjectURL(f));setSize({w:0,h:0});setZoom(1);setOffset({x:0,y:0});changed();e.target.value=""}
 function start(e:PointerEvent<HTMLDivElement>){if(!src||zoom<=1)return;drag.current={x:e.clientX,y:e.clientY,ox:offset.x,oy:offset.y};setMoving(true);e.currentTarget.setPointerCapture(e.pointerId)}
 function move(e:PointerEvent<HTMLDivElement>){if(!moving)return;setOffset(clamp(drag.current.ox+e.clientX-drag.current.x,drag.current.oy+e.clientY-drag.current.y));changed()}
 function end(e:PointerEvent<HTMLDivElement>){setMoving(false);if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId)}
 function zoomTo(z:number){const n=Math.max(1,Math.min(2.8,z));setZoom(n);requestAnimationFrame(()=>setOffset(o=>clamp(o.x,o.y)));changed()}
 async function apply(){const m=metrics(),i=img.current;if(applied||!m||!i||!size.w)return;try{const cv=document.createElement("canvas");cv.width=out[0];cv.height=out[1];const x=cv.getContext("2d");if(!x||!i.complete||!i.naturalWidth)throw new Error();const sw=Math.min(size.w,m.w/m.s),sh=Math.min(size.h,m.h/m.s),sx=Math.max(0,Math.min(size.w-sw,(size.w-sw)/2-offset.x/m.s)),sy=Math.max(0,Math.min(size.h-sh,(size.h-sh)/2-offset.y/m.s));x.imageSmoothingEnabled=true;x.imageSmoothingQuality="high";x.drawImage(i,sx,sy,sw,sh,0,0,out[0],out[1]);const b=await new Promise<Blob|null>((r,j)=>{try{cv.toBlob(r,"image/webp",.9)}catch(e){j(e)}});if(!b)throw new Error();onChange(new File([b],aspect==="square"?"ravine-avatar.webp":"ravine-cover.webp",{type:"image/webp"}));setDirty(false);setApplied(true)}catch{setError(true);setApplied(false)}}
 const m=size.w?metrics():null;const style=m?{width:m.iw,height:m.ih,left:`calc(50% - ${m.iw/2}px + ${offset.x}px)`,top:`calc(50% - ${m.ih/2}px + ${offset.y}px)`,transition:moving?"none":"transform 180ms cubic-bezier(.22,1,.36,1)",transform:"none",objectFit:"fill" as const}:undefined;
 return <div className={`ravine-media-picker ravine-media-picker--${aspect}`} dir={ar?"rtl":"ltr"}><input className="ravine-media-picker-input" ref={useRef<HTMLInputElement>(null)} type="file" accept="image/jpeg,image/png,image/webp" onChange={file}/><div className="ravine-media-picker-head"><div><span>{aspect==="square"?"1:1":"16:9"}</span><strong>{applied?c.applied:dirty?c.change:src?c.change:c.choose}</strong></div><span className="ravine-media-ratio">{aspect==="square"?"1:1":"16:9"}</span></div>{src?<><div ref={v} className={`ravine-media-crop${applied?" is-applied":""}`} onPointerDown={start} onPointerMove={move} onPointerUp={end} onPointerCancel={end} style={{aspectRatio:`${ratio}`}}><img ref={img} src={src} alt="" onLoad={()=>{const i=img.current;if(i)setSize({w:i.naturalWidth,h:i.naturalHeight})}} onError={()=>setError(true)} className="ravine-media-crop-image" style={style} draggable={false}/><div className="ravine-media-crop-frame"/>{applied&&<div className="ravine-media-crop-applied"><Check size={16}/><span>{c.applied}</span></div>}{zoom===1&&!applied&&<div className="ravine-media-crop-hint">{c.hint}</div>}</div><div className="ravine-media-controls"><button type="button" className="ravine-media-icon-button" onClick={()=>zoomTo(zoom-.1)} disabled={zoom<=1} aria-label={c.zoomOut}><Minus size={14}/></button><label className="ravine-media-zoom"><span>{Math.round(zoom*100)}%</span><input type="range" min="1" max="2.8" step=".01" value={zoom} onChange={e=>zoomTo(Number(e.target.value))} aria-label={ar?"تكبير الصورة":"Image zoom"}/></label><button type="button" className="ravine-media-icon-button" onClick={()=>zoomTo(zoom+.1)} disabled={zoom>=2.8} aria-label={c.zoomIn}><Plus size={14}/></button><button type="button" className="ravine-media-icon-button" onClick={()=>zoomTo(1)} aria-label={c.reset}><RotateCcw size={15}/></button><button type="button" className="ravine-media-change" onClick={()=>{document.querySelector<HTMLInputElement>(".ravine-media-picker-input")?.click()}}>{c.change}</button>{applied?<button type="button" className="ravine-media-applied" disabled><Check size={14}/>{c.applied}</button>:dirty?<button type="button" className="ravine-media-apply" onClick={()=>void apply()}><Check size={14}/>{c.apply}</button>:null}</div></>:<button type="button" className="ravine-media-empty" onClick={()=>document.querySelector<HTMLInputElement>(".ravine-media-picker-input")?.click()}><span className="ravine-media-empty-icon"><ImagePlus size={20}/></span><strong>{c.choose}</strong></button>}</div>
}