export type CommunityLocale = "ar" | "en";

export type CommunityCatalogItem = {
  slug: string;
  en: { name: string; eyebrow: string; description: string; details: string[] };
  ar: { name: string; eyebrow: string; description: string; details: string[] };
};

export const communityCatalog: CommunityCatalogItem[] = [
  { slug: "general", en: { name: "General community", eyebrow: "RAVINE / GENERAL", description: "A public preview space for the conversations shaping discovery across RAVINE.", details: ["Public conversation preview", "Discovery-oriented discussions", "No membership action is simulated"] }, ar: { name: "المجتمع العام", eyebrow: "رَافِين / العام", description: "مساحة عرض عامة للمحادثات التي تشكل الاكتشاف داخل رَافِين.", details: ["معاينة للمحادثات العامة", "نقاشات مرتبطة بالاكتشاف", "لا توجد عضوية وهمية"] } },
  { slug: "film", en: { name: "Film", eyebrow: "RAVINE / FILM", description: "A topic community for cinema, filmmaking and screen language.", details: ["Cinema & filmmaking", "Work-to-conversation discovery", "Public preview only"] }, ar: { name: "السينما", eyebrow: "رَافِين / السينما", description: "مجتمع موضوعي للسينما وصناعة الأفلام ولغة الصورة.", details: ["السينما وصناعة الأفلام", "اكتشاف من العمل إلى الحوار", "معاينة عامة فقط"] } },
  { slug: "photography", en: { name: "Photography", eyebrow: "RAVINE / PHOTOGRAPHY", description: "A topic community for photographic practice, visual storytelling and craft.", details: ["Photography practice", "Visual storytelling", "Public preview only"] }, ar: { name: "التصوير", eyebrow: "رَافِين / التصوير", description: "مجتمع موضوعي للممارسة الفوتوغرافية والسرد البصري والحرفة.", details: ["الممارسة الفوتوغرافية", "السرد البصري", "معاينة عامة فقط"] } },
  { slug: "editing", en: { name: "Editing", eyebrow: "RAVINE / EDITING", description: "A topic community around montage, rhythm, narrative structure and post-production craft.", details: ["Montage & rhythm", "Narrative structure", "Public preview only"] }, ar: { name: "المونتاج", eyebrow: "رَافِين / المونتاج", description: "مجتمع موضوعي للمونتاج والإيقاع والبنية السردية وحرفة ما بعد الإنتاج.", details: ["المونتاج والإيقاع", "البنية السردية", "معاينة عامة فقط"] } },
  { slug: "motion-vfx", en: { name: "Motion & VFX", eyebrow: "RAVINE / MOTION + VFX", description: "A topic community for motion design, visual effects and image-making systems.", details: ["Motion design", "Visual effects", "Public preview only"] }, ar: { name: "الحركة والمؤثرات", eyebrow: "رَافِين / الحركة + VFX", description: "مجتمع موضوعي للتصميم الحركي والمؤثرات البصرية وأنظمة صناعة الصورة.", details: ["التصميم الحركي", "المؤثرات البصرية", "معاينة عامة فقط"] } },
  { slug: "documentary", en: { name: "Documentary", eyebrow: "RAVINE / DOCUMENTARY", description: "A topic community for documentary practice, observation and real-world storytelling.", details: ["Documentary craft", "Observation & research", "Public preview only"] }, ar: { name: "الوثائقي", eyebrow: "رَافِين / الوثائقي", description: "مجتمع موضوعي للممارسة الوثائقية والملاحظة والسرد الواقعي.", details: ["حرفة الوثائقي", "الملاحظة والبحث", "معاينة عامة فقط"] } },
  { slug: "music", en: { name: "Music", eyebrow: "RAVINE / MUSIC", description: "A topic community for music creators, sound and audiovisual expression.", details: ["Music creation", "Sound & audiovisual work", "Public preview only"] }, ar: { name: "الموسيقى", eyebrow: "رَافِين / الموسيقى", description: "مجتمع موضوعي لصناع الموسيقى والصوت والتعبير السمعي البصري.", details: ["صناعة الموسيقى", "الصوت والعمل السمعي البصري", "معاينة عامة فقط"] } },
  { slug: "podcasts", en: { name: "Podcasts", eyebrow: "RAVINE / PODCASTS", description: "A topic community for audio programs, conversations and long-form listening.", details: ["Audio programs", "Long-form conversation", "Public preview only"] }, ar: { name: "البرامج الصوتية", eyebrow: "رَافِين / الصوتيات", description: "مجتمع موضوعي للبرامج الصوتية والحوار والاستماع طويل المدى.", details: ["البرامج الصوتية", "الحوار المطول", "معاينة عامة فقط"] } },
  { slug: "gaming", en: { name: "Gaming", eyebrow: "RAVINE / GAMING", description: "A topic community for games, play, creators and audiovisual gaming culture.", details: ["Games & play", "Gaming creators", "Public preview only"] }, ar: { name: "الألعاب", eyebrow: "رَافِين / الألعاب", description: "مجتمع موضوعي للألعاب والمحتوى الإبداعي وثقافة الألعاب السمعية البصرية.", details: ["الألعاب واللعب", "مبدعو الألعاب", "معاينة عامة فقط"] } },
  { slug: "creators-hub", en: { name: "Creator communities", eyebrow: "RAVINE / CREATORS", description: "A preview of creator-led spaces kept distinct from work comments.", details: ["Creator-led spaces", "Distinct from work comments", "Access rules remain open decisions"] }, ar: { name: "مجتمعات المبدعين", eyebrow: "رَافِين / المبدعون", description: "معاينة لمساحات يقودها المبدعون وتبقى منفصلة عن تعليقات الأعمال.", details: ["مساحات يقودها المبدعون", "منفصلة عن تعليقات الأعمال", "قواعد الوصول ما زالت قرارًا مفتوحًا"] } },
  { slug: "user-groups", en: { name: "User groups", eyebrow: "RAVINE / GROUPS", description: "A preview of user-created groups; eligibility and moderation rules remain open decisions.", details: ["User-created groups", "Interest & project spaces", "Eligibility remains open"] }, ar: { name: "مجموعات المستخدمين", eyebrow: "رَافِين / المجموعات", description: "معاينة للمجموعات التي ينشئها المستخدمون؛ الأهلية والإشراف ما زالا قرارات مفتوحة.", details: ["مجموعات ينشئها المستخدمون", "مساحات للاهتمامات والمشاريع", "الأهلية ما زالت مفتوحة"] } },
  { slug: "elite", en: { name: "Elite spaces", eyebrow: "RAVINE / ELITE", description: "A preview of rare spaces intended to activate later under explicit criteria.", details: ["Rare / special spaces", "Explicit criteria required", "Not automatically open"] }, ar: { name: "مساحات النخبة", eyebrow: "رَافِين / النخبة", description: "معاينة لمساحات نادرة يُقصد تفعيلها لاحقًا وفق معايير واضحة.", details: ["مساحات نادرة وخاصة", "تتطلب معايير واضحة", "ليست مفتوحة تلقائيًا"] } },
];

export function getCommunity(slug: string) {
  return communityCatalog.find((item) => item.slug === slug) ?? null;
}
