-- RAVINE Work Universe v1 — staged schema.
-- Intentionally NOT applied by this execution.
-- Compatibility strategy: existing public.videos remains the playback-backed legacy source;
-- new Work records can point to a legacy video while richer Work context grows independently.

create table if not exists public.ravine_works (
  id bigint generated by default as identity primary key,
  legacy_video_id bigint unique references public.videos(id) on delete set null,
  creator_id bigint references public.creators(id) on delete set null,
  title text not null,
  description text,
  work_type text not null default 'video' check (work_type in ('short','video','film','documentary','podcast','live')),
  status text not null default 'draft' check (status in ('draft','processing','published','unlisted','archived')),
  visibility text not null default 'public' check (visibility in ('public','followers','members','tier','invite_only','private')),
  discovery_enabled boolean not null default true,
  poster_url text,
  artwork_url text,
  access_policy text not null default 'public' check (access_policy in ('public','followers','members','tier','invite_only')),
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists ravine_works_creator_idx on public.ravine_works(creator_id, created_at desc);
create index if not exists ravine_works_type_status_idx on public.ravine_works(work_type, status, published_at desc);
create index if not exists ravine_works_legacy_video_idx on public.ravine_works(legacy_video_id);

create table if not exists public.ravine_work_people (
  work_id bigint not null references public.ravine_works(id) on delete cascade,
  person_kind text not null check (person_kind in ('creator','director','producer','host','guest','cast','crew','editor','composer','other')),
  display_name text not null,
  role_label text,
  creator_id bigint references public.creators(id) on delete set null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  primary key (work_id, person_kind, display_name, sort_order)
);

create table if not exists public.ravine_work_collections (
  work_id bigint not null references public.ravine_works(id) on delete cascade,
  collection_type text not null check (collection_type in ('series','season','show','event','project')),
  external_id text,
  title text not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  primary key (work_id, collection_type, sort_order)
);

create table if not exists public.ravine_work_context (
  work_id bigint primary key references public.ravine_works(id) on delete cascade,
  context_en text,
  context_ar text,
  bts_url text,
  credits_text_en text,
  credits_text_ar text,
  trailer_asset_id bigint references public.work_media_assets(id) on delete set null,
  preview_asset_id bigint references public.work_media_assets(id) on delete set null,
  updated_at timestamptz not null default now()
);

create or replace view public.ravine_work_catalog as
select
  w.id,
  w.legacy_video_id,
  w.creator_id,
  w.title,
  w.description,
  w.work_type,
  w.status,
  w.visibility,
  w.discovery_enabled,
  w.poster_url,
  w.artwork_url,
  w.access_policy,
  w.published_at,
  v.video_url as legacy_media_url,
  v.duration as legacy_duration,
  v.thumbnail_url as legacy_thumbnail_url,
  v.views as legacy_views,
  v.likes as legacy_likes,
  c.name as creator_name,
  c.username as creator_username
from public.ravine_works w
left join public.videos v on v.id = w.legacy_video_id
left join public.creators c on c.id = w.creator_id;

alter table public.ravine_works enable row level security;
alter table public.ravine_work_people enable row level security;
alter table public.ravine_work_collections enable row level security;
alter table public.ravine_work_context enable row level security;

-- Public discovery read is deliberately limited to published/public/discoverable Work records.
drop policy if exists ravine_work_public_read on public.ravine_works;
create policy ravine_work_public_read
on public.ravine_works
for select
using (status = 'published' and visibility = 'public' and discovery_enabled = true);

-- Creator-owned Work writes. Exact role verification/RLS helper functions remain a separate security phase.
drop policy if exists ravine_work_owner_insert on public.ravine_works;
create policy ravine_work_owner_insert
on public.ravine_works
for insert
with check (
  exists (
    select 1
    from public.creators c
    where c.id = creator_id
      and c.user_id = auth.uid()
  )
);

drop policy if exists ravine_work_owner_update on public.ravine_works;
create policy ravine_work_owner_update
on public.ravine_works
for update
using (
  exists (
    select 1
    from public.creators c
    where c.id = creator_id
      and c.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.creators c
    where c.id = creator_id
      and c.user_id = auth.uid()
  )
);

-- Do not silently broaden write access on the contextual child tables before the full creator-role audit.
